apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: eshop/catalog.api:latest
          ports:
            - containerPort: 80
          env:
            # SQL Server connection string pakai FQDN + port 1433
            - name: ConnectionStrings__CatalogDB
              value: "Server=sqlserver.default.svc.cluster.local,1433;Database=CatalogDb;User Id=sa;Password=Password123!"

            # RabbitMQ connection
            # - name: EventBusConnection
            #   value: "rabbitmq.default.svc.cluster.local"
            # - name: EventBusUserName
            #   value: "admin"
            # - name: EventBusPassword
            #   value: "admin123"
            # - name: ConnectionStrings__CatalogDb
            #   value: "Server=sqlserver.default.svc.cluster.local,1433;Database=CatalogDb;User Id=sa;Password=Password123!"

            - name: EventBus__Connection
              value: "rabbitmq.default.svc.cluster.local"
            - name: EventBus__UserName
              value: "admin"
            - name: EventBus__Password
              value: "admin123"

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  namespace: default
spec:
  selector:
    app: catalog-api
  ports:
    - port: 80
      targetPort: 80
