apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
        - name: identity-api
          image: eshop/identity.api:latest   # ganti sesuai image kamu
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__IdentityDb
              value: "Server=sqlserver;Database=IdentityDb;User Id=sa;Password=Password123!"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: default
spec:
  selector:
    app: identity-api
  ports:
    - port: 80
      targetPort: 80
